baseURL = 'https://akira.sh/'
languageCode = 'en-us'
title = 'akira.sh'
theme = "nightfall"

[params]
user = "s0ders"
hostname = "akira.sh"
SiteDescription = "Yet another software engineering blog"
footerHtml = " "

  [params.author]
    name = "Maxime T."
    email = "s0ders[at]pm.me"

  [[params.social]]
  key = 0
  name = "github"
  url = "https://github.com/s0ders"
  icon = "github"  

  [[params.social]]
  key = 1
  name = "linkedin"
  url = "https://www.linkedin.com/in/maxime-tueux"
  icon = "linkedin"  

  [[params.social]]
  key = 2
  name = "rss"
  url = "https://akira.sh/index.xml"
  icon = "rss"

  [[params.social]]
    key = 3
    name = "mail"
    url = "mailto:s0ders@akira.sh"
    icon = "mail"

[[params.meta]]
  favicon = true
  description = "Personnal blog of a Go software engineer"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "/posts"
  
  [[menu.header]]
    name = "books"
    weight = 5
    url = "/books"

  [[menu.header]]
    name = "about"
    weight = 10
    url = "/about"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

