baseURL = 'https://akira.sh/'
languageCode = 'en-us'
title = 'akira.sh'
theme = "nightfall"

[params]
user = "s0ders"
hostname = "akira.sh"
SiteDescription = "Yet another software engineering blog"
footerHtml = " "

  [params.author]
    name = "Maxime T."
    email = "s0ders[at]pm.me"

  [[params.social]]
  key = 0
  name = "github"
  url = "https://github.com/s0ders"
  icon = "fa-brands fa-github"  

  [[params.social]]
  key = 1
  name = "linkedin"
  url = "https://www.linkedin.com/in/maxime-tx"
  icon = "fa-brands fa-linkedin"  


  [[params.meta]]
  favicon = true
  description = "Personnal blog of a Go software engineer"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 2
    url = "/posts"
  
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

