name: Hugo build and deploy
on:
  push:
    branches:
      - "main"

defaults:
  run:
    shell: bash

jobs:
  gitleaks:
    name: Secret leaks detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: gitleaks/gitleaks-action@83373cf2f8c4db6e24b41c1a9b086bb9619e9cd3 # v2.3.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spell:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    needs:
      - gitleaks
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: typos-action
        uses: crate-ci/typos@2872c382bb9668d4baa5eade234dcbc0048ca2cf # v1.28.2

  build-and-deploy:
    runs-on: ubuntu-latest
    needs:
      - spell
    env:
      HUGO_VERSION: 0.142.0
    steps:

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Setup SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          set -x  # Enable verbose debugging output
          mkdir -p /home/runner/.ssh
          
          # Print out SSH key details (without showing actual key)
          echo "${{ secrets.SSH_KEY }}" | wc -c
          echo "${{ secrets.SSH_KEY }}" | head -c 10
          
          # Verbose SSH key handling
          ssh-keyscan ${{ secrets.SERVER_IP }} >> /home/runner/.ssh/known_hosts
          
          echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          
          # Additional diagnostics
          ls -l /home/runner/.ssh/
          cat /home/runner/.ssh/known_hosts
          
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
          
          # Test SSH connection
          ssh -v -i /home/runner/.ssh/github_actions ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} exit || true

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build akira.sh with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --gc --minify --destination ./public/ build

      - name: Deploy using rsync
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          rsync --delete -avz ./public/* github_actions@${{ secrets.SERVER_IP }}:/var/www/html/akira/
          rsync --delete -avz ./onion/* github_actions@${{ secrets.SERVER_IP }}:/var/www/html/akira_onion/
